### ISSUE TITLE
Exported MBTiles not functional

### ISSUE THREAD

**Issue by geo-tech** [syncpoint/openvtpk#7]
At the moment the created MBTiles from basemap.at is not functional, i cant use it on tileserver-gl (only empty pbf´s would be served). And for example in QGIS its not possible to load the created MBTiles.

**Comment by ThomasHalwax** [comment]
Can you please try to view the tiles using Mapbox´ [mbview](https://github.com/mapbox/mbview)

**Comment by ThomasHalwax** [comment]
The metadata in the mbtiles container has incorrect values for the ```bounds``` property (ymin = ymax). I will investigate this issue and find out if it's a problem with the VTPK or with my code.

**Comment by geo-tech** [comment]
Thank you, with the new Version it working well.
