### ISSUE TITLE
VTPK Bug related to node.js

### ISSUE THREAD

**Issue by michaelradhuber** [syncpoint/openvtpk#9]
`root@SHARE-SERVER:~/Downloads# openvtpk/bin/run inspect bmapv_vtpk_3857.vtpk
inspecting VTPK at bmapv_vtpk_3857.vtpk
Error: ENOTDIR: not a directory, scandir 'bmapv_vtpk_3857.vtpk/p12/tile'
    at Object.enumerateLevels (~/Downloads/openvtpk/src/shared/content.js:9:34)
    at inspect (~/Downloads/openvtpk/src/shared/inspect.js:9:31)
`

Ubuntu 18.04.4 LTS
Node v10.19.0
npm 6.13.7
nvm 0.34.0

Looks like a node related error, already tried to set an alias in nvm, tried to export node_modules directory to $NODE_PATH, didn't help.

Any help greatly appreciated, Thx

**Comment by michaelradhuber** [comment]
Sorry, I should read the docs more carefully before posting....

> OpenVTPK expects the VTPK package to be unzipped into a folder of your choice. Later on this 

> folder will be referred to as SOURCEFOLDER.

**Comment by ThomasHalwax** [comment]
Thanks for the issue, I will take care of this and show a helpful warning if the user provides a file instead of a folder.

**Comment by ThomasHalwax** [comment]
v0.2.2 fixes this problem
